### ISSUE TITLE
A JavaScript error occurred in the main process Uncaught Exception: ReferenceError: _statics is not defined at App.

### ISSUE THREAD

**Issue by churchilldu** [dale0525/ClipBroad#1]
![image](https://user-images.githubusercontent.com/62705137/134670348-5f6f495c-cc06-46ef-90ea-5663afcbe7f1.png)

**Comment by dale0525** [comment]
Are you using Windows x32?
Would you please varify if this update solves the issue?
https://github.com/dale0525/ClipBroad/releases/tag/v1.0.2

**Comment by churchilldu** [comment]
>Device name	
Processor	Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz   2.40 GHz
Installed RAM	8.00 GB
Device ID	7D9E295F-2CA7-46D4-9F78-F7F163B1B345
Product ID	00391-90280-00000-AA404
System type	64-bit operating system, x64-based processor
Pen and touch	Pen support
 
nope,I'm using win10X64
but 1.0.2 works now,thanks
