### ISSUE TITLE
can't login github

### ISSUE THREAD

**Issue by churchilldu** [dale0525/ClipBroad#2]

**Comment by churchilldu** [comment]
https://user-images.githubusercontent.com/62705137/134841504-93f3534b-3ba9-409a-8c30-2f25b03e1fef.mp4

**Comment by churchilldu** [comment]
I have tried several times to login but failed. My internet connection is fine

**Comment by dale0525** [comment]
I believe your browser is preventing it from redirecting back to the app.
Can you try:
1. open the browser's dev tool by pressing F12, go to the "console" tab, and attempt to login again
2. directly visiting the following url in the browser to see what happens: "clipbroad://1" (without quote)

**Comment by churchilldu** [comment]
I tried to use firefox instead chrome
The first time I login succed and receive the email from github,
>A third-party OAuth application (ClipBroad) with repo scope was recently authorized to access your account.


but the app still keep not loging in. When I tried again, the situation became same as the video.
![image](https://user-images.githubusercontent.com/62705137/135056089-990dba2c-4498-48e2-8be4-477db98bb37d.png)

opening  the browser's dev tool doesn't work
visting  "clipboard://1" just nothing

**Comment by dale0525** [comment]
It seems the app failed to register the "clipbroad://" protocol to the system due to your previous launching issue. Would you please try to uninstall the app and download the latest version to try again?

**Comment by churchilldu** [comment]
> It seems the app failed to register the "clipbroad://" protocol to the system due to your previous launching issue. Would you please try to uninstall the app and download the latest version to try again?

I reinstall the app and it succeed! Thanks for your work and in-time reply.
