### ISSUE TITLE
安卓端无法使用github客户端进行登录

### ISSUE THREAD

**Issue by EvatsugDnalloR** [dale0525/ClipBroad#3]
点击登陆后唤起github客户端，然后就会持续无响应的黑屏。如果用浏览器打开通过网页端来登录就没有问题。不是大问题但望修复

**Comment by dale0525** [comment]
> 点击登陆后唤起github客户端，然后就会持续无响应的黑屏。如果用浏览器打开通过网页端来登录就没有问题。不是大问题但望修复

我尝试复现这个问题，但是我的安卓设备上即使安装了Github客户端，点击登录时打开的依然是系统默认浏览器，无法唤起Github客户端。是有什么设置吗？

**Comment by EvatsugDnalloR** [comment]
> > 点击登陆后唤起github客户端，然后就会持续无响应的黑屏。如果用浏览器打开通过网页端来登录就没有问题。不是大问题但望修复
> 
> 我尝试复现这个问题，但是我的安卓设备上即使安装了Github客户端，点击登录时打开的依然是系统默认浏览器，无法唤起Github客户端。是有什么设置吗？

一般在应用程序设置里应该有打开链接的设置的，里面可以设置用来打开链接的应用

**Comment by dale0525** [comment]
Github Oauth链接是普通https链接，默认由浏览器打开，我目前也没法重现该问题，且不影响正常使用，暂时不处理。
